### PR TITLE
Use wayland by default

### PR DESCRIPTION
**Pull request by Etaash-mathamsetty**
It works really well and works just like x11 does. There are a few issues when changing resolution and monitors, but a restart of the game fixes that and once set correctly it works perfectly.

### CODE REVIEW

**Comment by mbugni** [comment]
> There are a few issues when changing resolution and monitors, but a restart of the game fixes that and once set correctly it works perfectly.

These issues has been detected during early stage of development, and are exactly the reason why a full-Wayland support has not been enabled.

AFAIK, the game has no official Wayland support. At the opposite, many issues are reported under Wayland especially for older versions like this one.

I really don't understand why we need to intruduce issues that can be simply avoided, maybe you can better explain your reasons.

**Comment by Etaash-mathamsetty** [comment]
> > There are a few issues when changing resolution and monitors, but a restart of the game fixes that and once set correctly it works perfectly.
> 
> These issues has been detected during early stage of development, and are exactly the reason why a full-Wayland support has not been enabled.
> 
> AFAIK, the game has no official Wayland support. At the opposite, many issues are reported under Wayland especially for older versions like this one.
> 
> I really don't understand why we need to intruduce issues that can be simply avoided, maybe you can better explain your reasons.
> 
> 

I was under the impression that it didn't work at all and so made a PR when I realized it did work. Yes it's not stable for this project yet, but it can be in the future, so I'll leave this open.

There's no such thing as this game doesn't have full wayland support, unless the game decides it write their own API to control windows and their creation, which no sane person does, almost everyone uses either GLFW or SDL

**Comment by mbugni** [comment]
> I was under the impression that it didn't work at all and so made a PR when I realized it did work. Yes it's not stable for this project yet, but it can be in the future, so I'll leave this open.
> 

There is no future for this project, because it's on a dead branch. Current development is focused on Vulkan version. The main reason an OpenGL flatpak exists it's because current Vulkan development doesn't support some GPUs and it's slower using older hardware.

**Comment by Etaash-mathamsetty** [comment]
> > I was under the impression that it didn't work at all and so made a PR when I realized it did work. Yes it's not stable for this project yet, but it can be in the future, so I'll leave this open.
> 
> There is no future for this project, because it's on a dead branch. Current development is focused on Vulkan version. The main reason an OpenGL flatpak exists it's because current Vulkan development doesn't support some GPUs and it's slower using older hardware.

might be worth adding a flag that switches between opengl and vulkan

**Comment by Etaash-mathamsetty** [comment]
seems like you guys use SDL2, so I guess ill look into it and see and what's going on

**Comment by mbugni** [comment]
> might be worth adding a flag that switches between opengl and vulkan

I'm not sure you understand. Version 1.4.0 (this one) is the latest version that supports OpenGL. Newer versions are based on Vulkan. If you want to submit patches, please refer to [upstream project](https://github.com/RobertBeckebans/RBDOOM-3-BFG).

This app will remain on OpenGL.

**Comment by Etaash-mathamsetty** [comment]
> > might be worth adding a flag that switches between opengl and vulkan
> 
> I'm not sure you understand. Version 1.4.0 (this one) is the latest version that supports OpenGL. Newer versions are based on Vulkan. If you want to submit patches, please refer to [upstream project](https://github.com/RobertBeckebans/RBDOOM-3-BFG).
> 
> This app will remain on OpenGL.

thanks for explaining, I get it now

**Pull request closed without merging**
